# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# Trajectory controllers for moveit-------------------------------------
follow_joint_trajectory:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - rev1
    - rev2
    - rev3
    - rev4
    - rev5
    - rev6
  gains:
    rev1: {p: 100.0, i: 0.01, d: 10.0}
    rev2: {p: 100.0, i: 0.01, d: 10.0}
    rev3: {p: 100.0, i: 0.01, d: 10.0}
    rev4: {p: 100.0, i: 0.01, d: 10.0}
    rev5: {p: 100.0, i: 0.01, d: 10.0}
    rev6: {p: 100.0, i: 0.01, d: 10.0}